title: Franz Geffke
description: "Full-Stack Developer, AI Orchestrator, ½ Machine - Personal website and blog covering web development, AI integration, system architecture, and technology insights"
baseurl: ""
url: "https://gofranz.com"
destination: _site/
mapbox_token: "pk.eyJ1IjoiZGtrbWEiLCJhIjoiU05aOVdrRSJ9._Ahj-qQ5cCyLUCM2dp4tAw"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

pagination:
  enabled: true
  per_page: 20
  permalink: '/blog/page/:num/'

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - node_modules
  - vendor
  - .gitlab-ci.yml
  - src
  - README.md
  - CLAUDE.md
  - deploy.sh
  - Dockerfile
  - esbuild.config.js
  - TRAIL.md
  - TODO.md

collections:
  posts:
    output: true
    permalink: /blog/:title/
  work:
    output: true
    permalink: /work/:title/
  clients:
    output: true
    permalink: /client/:title/
  testimonials:
    output: false
  til:
    output: true
    permalink: /til/:title/
